// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOcsIFJfH2AuXYMethMwx5KSXXryvGYPk',
    appId: '1:1029008670754:web:9e4a7b33b765c5bffe4a7b',
    messagingSenderId: '1029008670754',
    projectId: 'newstak-d2daa',
    authDomain: 'newstak-d2daa.firebaseapp.com',
    storageBucket: 'newstak-d2daa.appspot.com',
    measurementId: 'G-BRZEG5FH4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUU4UNhjERQ7MjxoqNj78fMwR1kkm-xgY',
    appId: '1:1029008670754:android:f7dc3a33c8c84068fe4a7b',
    messagingSenderId: '1029008670754',
    projectId: 'newstak-d2daa',
    storageBucket: 'newstak-d2daa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClCDunzkAsF5lCftatGOBdwbZ3e2DLsB8',
    appId: '1:1029008670754:ios:61a6dbdb6990d3f0fe4a7b',
    messagingSenderId: '1029008670754',
    projectId: 'newstak-d2daa',
    storageBucket: 'newstak-d2daa.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClCDunzkAsF5lCftatGOBdwbZ3e2DLsB8',
    appId: '1:1029008670754:ios:61a6dbdb6990d3f0fe4a7b',
    messagingSenderId: '1029008670754',
    projectId: 'newstak-d2daa',
    storageBucket: 'newstak-d2daa.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOcsIFJfH2AuXYMethMwx5KSXXryvGYPk',
    appId: '1:1029008670754:web:81dbbd1be68f1310fe4a7b',
    messagingSenderId: '1029008670754',
    projectId: 'newstak-d2daa',
    authDomain: 'newstak-d2daa.firebaseapp.com',
    storageBucket: 'newstak-d2daa.appspot.com',
    measurementId: 'G-6TZGZTPHCV',
  );
}
